<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AdminController;
use Cake\Event\Event;

/**
 * Kikokukibous Controller
 *
 *
 * @method \App\Model\Entity\Kikokukibous[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class KikokukibousController extends AdminController
{

    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
        $this->viewBuilder()->layout('admin');
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $this->paginate = ['limit' => 10];
        $kikokukibous = $this->paginate($this->Kikokukibous);

        $this->set(compact('kikokukibous'));
    }

    /**
     * View method
     *
     * @param string|null $id Kikokukibous id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $kikokukibous = $this->Kikokukibous->get($id, [
            'contain' => []
        ]);

        $this->set('kikokukibous', $kikokukibous);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $kikokukibou = $this->Kikokukibous->newEntity();
        if ($this->request->is('post')) {
            $kikokukibou = $this->Kikokukibous->patchEntity($kikokukibou, $this->request->getData());
            if ($this->Kikokukibous->save($kikokukibou)) {
                $this->Flash->success(__('The kikokukibous has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The kikokukibous could not be saved. Please, try again.'));
        }
        $this->set(compact('kikokukibou'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Kikokukibous id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $kikokukibou = $this->Kikokukibous->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $kikokukibou = $this->Kikokukibous->patchEntity($kikokukibou, $this->request->getData());
            if ($this->Kikokukibous->save($kikokukibou)) {
                $this->Flash->success(__('The kikokukibous has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The kikokukibous could not be saved. Please, try again.'));
        }
        $this->set(compact('kikokukibou'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Kikokukibous id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $kikokukibou = $this->Kikokukibous->get($id);
        if ($this->Kikokukibous->delete($kikokukibou)) {
            $this->Flash->success(__('The kikokukibous has been deleted.'));
        } else {
            $this->Flash->error(__('The kikokukibous could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
