<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AdminController;
use Cake\Event\Event;

/**
 * Rainichimokutekis Controller
 *
 *
 * @method \App\Model\Entity\Rainichimokuteki[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class RainichimokutekisController extends AdminController
{

    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
        $this->viewBuilder()->layout('admin');
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $this->paginate = ['limit' => 10];
        $rainichimokutekis = $this->paginate($this->Rainichimokutekis);

        $this->set(compact('rainichimokutekis'));
    }

    /**
     * View method
     *
     * @param string|null $id Rainichimokuteki id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $rainichimokuteki = $this->Rainichimokutekis->get($id, [
            'contain' => []
        ]);

        $this->set('rainichimokuteki', $rainichimokuteki);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $rainichimokuteki = $this->Rainichimokutekis->newEntity();
        if ($this->request->is('post')) {
            $rainichimokuteki = $this->Rainichimokutekis->patchEntity($rainichimokuteki, $this->request->getData());
            if ($this->Rainichimokutekis->save($rainichimokuteki)) {
                $this->Flash->success(__('The rainichimokuteki has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The rainichimokuteki could not be saved. Please, try again.'));
        }
        $this->set(compact('rainichimokuteki'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Rainichimokuteki id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $rainichimokuteki = $this->Rainichimokutekis->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $rainichimokuteki = $this->Rainichimokutekis->patchEntity($rainichimokuteki, $this->request->getData());
            if ($this->Rainichimokutekis->save($rainichimokuteki)) {
                $this->Flash->success(__('The rainichimokuteki has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The rainichimokuteki could not be saved. Please, try again.'));
        }
        $this->set(compact('rainichimokuteki'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Rainichimokuteki id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $rainichimokuteki = $this->Rainichimokutekis->get($id);
        if ($this->Rainichimokutekis->delete($rainichimokuteki)) {
            $this->Flash->success(__('The rainichimokuteki has been deleted.'));
        } else {
            $this->Flash->error(__('The rainichimokuteki could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
