<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AdminController;
use Cake\Event\Event;

/**
 * Shokygyous Controller
 *
 *
 * @method \App\Model\Entity\Shokugyous[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ShokugyousController extends AdminController
{

    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
        $this->viewBuilder()->layout('admin');
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $this->paginate = ['limit' => 10];
        $shokugyous = $this->paginate($this->Shokugyous);

        $this->set(compact('shokugyous'));
    }

    /**
     * View method
     *
     * @param string|null $id Shokygyous id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $shokugyous = $this->Shokugyous->get($id, [
            'contain' => []
        ]);

        $this->set('shokugyous', $shokugyous);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $shokugyou = $this->Shokugyous->newEntity();
        if ($this->request->is('post')) {
            $shokugyou = $this->Shokugyous->patchEntity($shokugyou, $this->request->getData());
            if ($this->Shokugyous->save($shokugyou)) {
                $this->Flash->success(__('The shokugyou has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The shokugyou could not be saved. Please, try again.'));
        }
        $this->set(compact('shokugyou'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Shokygyous id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $shokugyou = $this->Shokugyous->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $shokugyou = $this->Shokugyous->patchEntity($shokugyou, $this->request->getData());
            if ($this->Shokugyous->save($shokugyou)) {
                $this->Flash->success(__('The shokygyous has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The shokugyous could not be saved. Please, try again.'));
        }
        $this->set(compact('shokugyou'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Shokygyous id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $shokugyous = $this->Shokugyous->get($id);
        if ($this->Shokugyous->delete($shokugyous)) {
            $this->Flash->success(__('The shokugyous has been deleted.'));
        } else {
            $this->Flash->error(__('The shokugyous could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
