<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AdminController;
use Cake\Event\Event;

/**
 * Shuumis Controller
 *
 *
 * @method \App\Model\Entity\Shuumi[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ShuumisController extends AdminController
{
    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
        $this->viewBuilder()->layout('admin');
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $this->paginate = ['limit' => 10];
        $shuumis = $this->paginate($this->Shuumis);

        $this->set(compact('shuumis'));
    }

    /**
     * View method
     *
     * @param string|null $id Shuumi id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $shuumi = $this->Shuumis->get($id, [
            'contain' => []
        ]);

        $this->set('shuumi', $shuumi);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $shuumi = $this->Shuumis->newEntity();
        if ($this->request->is('post')) {
            $shuumi = $this->Shuumis->patchEntity($shuumi, $this->request->getData());
            if ($this->Shuumis->save($shuumi)) {
                $this->Flash->success(__('The shuumi has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The shuumi could not be saved. Please, try again.'));
        }
        $this->set(compact('shuumi'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Shuumi id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $shuumi = $this->Shuumis->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $shuumi = $this->Shuumis->patchEntity($shuumi, $this->request->getData());
            if ($this->Shuumis->save($shuumi)) {
                $this->Flash->success(__('The shuumi has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The shuumi could not be saved. Please, try again.'));
        }
        $this->set(compact('shuumi'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Shuumi id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $shuumi = $this->Shuumis->get($id);
        if ($this->Shuumis->delete($shuumi)) {
            $this->Flash->success(__('The shuumi has been deleted.'));
        } else {
            $this->Flash->error(__('The shuumi could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
